# Generated by Django 6.0 on 2026-02-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
