# Generated by Django 6.0 on 2026-02-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
