# Generated by Django 6.0 on 2026-02-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactThread',
        ),
    ]
